(cl:in-package umnitsa_rpi-msg)
(cl:export '(B-VAL
          B
          A-VAL
          A
          Y-VAL
          Y
          X-VAL
          X
          L-VAL
          L
          R-VAL
          R
          ZL-VAL
          ZL
          ZR-VAL
          ZR
          MINUS-VAL
          MINUS
          PLUS-VAL
          PLUS
          LCLICK-VAL
          LCLICK
          RCLICK-VAL
          RCLICK
          HOME-VAL
          HOME
          CAPTURE-VAL
          CAPTURE
          UP-VAL
          UP
          RIGHT-VAL
          RIGHT
          LTOGRIGHT-VAL
          LTOGRIGHT
          LTOGUP-VAL
          LTOGUP
          RTOGRIGHT-VAL
          RTOGRIGHT
          RTOGUP-VAL
          RTOGUP
))